spring:
  main:
    web-environment: false

messageRecover:
  inputBindingRemovalDelayInSec: 5
  rabbitMQProp:
    exchangeName: usi-1:submission-exchange
    deadLetterExchangeName: usi-1:dead-letter-exchange
    deadLetterQueueName: usi-submission-dead-letter
  qdbProp:
    baseURL: http://mac-subs-009:9554
    queue:
      deadLetterQueueName: failed_messages_queue
      basePath: /q
      inputBasePath: /in
      outputBasePath: /out
      inputPath: /fromRabbit
      outputPath: /toRabbit
      maxSize: 1g
      maxPayloadSize: 10m
      contentType: "application/json; charset=utf-8"
    messageFilter:
      grep:
      from:
      to:
      routingKey: this.is.a.routing.key
      fromId:


logging:
  level: debug


